# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(278, 386)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.student_name = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.student_name.setGeometry(QtCore.QRect(100, 40, 113, 20))
        self.student_name.setObjectName("student_name")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(16, 40, 81, 20))
        self.label.setObjectName("label")
        self.num_attempts = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.num_attempts.setGeometry(QtCore.QRect(100, 90, 113, 20))
        self.num_attempts.setObjectName("num_attempts")
        self.score1_entry = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.score1_entry.setGeometry(QtCore.QRect(100, 140, 113, 20))
        self.score1_entry.setObjectName("score1_entry")
        self.score2_entry = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.score2_entry.setGeometry(QtCore.QRect(100, 170, 113, 20))
        self.score2_entry.setObjectName("score2_entry")
        self.score3_entry = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.score3_entry.setGeometry(QtCore.QRect(100, 200, 113, 20))
        self.score3_entry.setObjectName("score3_entry")
        self.score4_entry = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.score4_entry.setGeometry(QtCore.QRect(100, 230, 113, 20))
        self.score4_entry.setObjectName("score4_entry")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 90, 81, 20))
        self.label_2.setObjectName("label_2")
        self.score1_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.score1_label.setGeometry(QtCore.QRect(30, 140, 47, 13))
        self.score1_label.setObjectName("score1_label")
        self.score2_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.score2_label.setGeometry(QtCore.QRect(30, 170, 47, 13))
        self.score2_label.setObjectName("score2_label")
        self.score3_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.score3_label.setGeometry(QtCore.QRect(30, 200, 47, 13))
        self.score3_label.setObjectName("score3_label")
        self.score4_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.score4_label.setGeometry(QtCore.QRect(30, 230, 47, 13))
        self.score4_label.setObjectName("score4_label")
        self.submit = QtWidgets.QPushButton(parent=self.centralwidget)
        self.submit.setGeometry(QtCore.QRect(60, 310, 141, 23))
        self.submit.setObjectName("submit")
        self.main_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.main_label.setGeometry(QtCore.QRect(40, 270, 211, 21))
        self.main_label.setObjectName("main_label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 278, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Student name:"))
        self.label_2.setText(_translate("MainWindow", "No of attempts:"))
        self.score1_label.setText(_translate("MainWindow", "Score 1:"))
        self.score2_label.setText(_translate("MainWindow", "Score 2:"))
        self.score3_label.setText(_translate("MainWindow", "Score 3:"))
        self.score4_label.setText(_translate("MainWindow", "Score 4:"))
        self.submit.setText(_translate("MainWindow", "SUBMIT"))
        self.main_label.setText(_translate("MainWindow", "Enter name and attempts then submit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
